/var/www/GIA/*.log {
    daily
    missingok
    rotate 7
    compress
    notifempty
    copytruncate
}

/var/www/GIA/backend/training/*.log {
    weekly
    missingok
    rotate 4
    compress
    notifempty
    copytruncate
}
